/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author hamda
 */
public class AdminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form ProfileAdmin
     */
    public AdminUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        KIPPanel = new javax.swing.JPanel();
        KabKotaLabel = new javax.swing.JLabel();
        TahunLabel = new javax.swing.JLabel();
        ProvinsiLabel = new javax.swing.JLabel();
        KecamatanLabel = new javax.swing.JLabel();
        KodeKJULabel = new javax.swing.JLabel();
        NoUrutLabel = new javax.swing.JLabel();
        NamaPerusahaanLabel = new javax.swing.JLabel();
        AlamatLabel = new javax.swing.JLabel();
        NoTelepoLabel = new javax.swing.JLabel();
        NoFaxLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        BentukBadanHukumLabel = new javax.swing.JLabel();
        KodeKJUTextField = new javax.swing.JTextField();
        TahunTextField = new javax.swing.JTextField();
        ProvinsiComboBox = new javax.swing.JComboBox<>();
        KabKotaComboBox = new javax.swing.JComboBox<>();
        KecamatanComboBox = new javax.swing.JComboBox<>();
        NoUrutTextField = new javax.swing.JTextField();
        NamaPerusahaanTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlamatTextArea = new javax.swing.JTextArea();
        NoTeleponTextField = new javax.swing.JTextField();
        NoFaxTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        BentukBadanHukumComboBox = new javax.swing.JComboBox<>();
        KIPJudulPanel = new javax.swing.JPanel();
        KIPJudulLabel = new javax.swing.JLabel();
        errorTahun = new javax.swing.JLabel();
        errorKJU = new javax.swing.JLabel();
        errorNoKabKot = new javax.swing.JLabel();
        errorPerusahaan = new javax.swing.JLabel();
        errorAlamat = new javax.swing.JLabel();
        errorTelepon = new javax.swing.JLabel();
        errorFax = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        DPPPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        StatusPerusahaanLabel = new javax.swing.JLabel();
        StatusKunjunganLabel = new javax.swing.JLabel();
        SubsektorLabel = new javax.swing.JLabel();
        TanamanPanganLabel = new javax.swing.JLabel();
        HortikulturaLabel = new javax.swing.JLabel();
        PerkebunanLabel = new javax.swing.JLabel();
        PeternakanLabel = new javax.swing.JLabel();
        KehutananLabel = new javax.swing.JLabel();
        PerikananLabel = new javax.swing.JLabel();
        UsahaUtamaLabel = new javax.swing.JLabel();
        StatuKunjunganBox = new javax.swing.JComboBox<>();
        StatusPerusahanBox = new javax.swing.JComboBox<>();
        TanamanPanganComboBox = new javax.swing.JComboBox<>();
        HortikulturaComboBox = new javax.swing.JComboBox<>();
        KakaoCokelatCheckBox = new javax.swing.JCheckBox();
        KaretCheckBox = new javax.swing.JCheckBox();
        KelapaSawitCheckBox = new javax.swing.JCheckBox();
        KopiCheckBox = new javax.swing.JCheckBox();
        TehCheckBox = new javax.swing.JCheckBox();
        TebuCheckBox = new javax.swing.JCheckBox();
        TembakauCheckBox = new javax.swing.JCheckBox();
        CengkehCheckBox = new javax.swing.JCheckBox();
        KelapaCheckBox = new javax.swing.JCheckBox();
        LadaCheckBox = new javax.swing.JCheckBox();
        TanamanLainCheckBox = new javax.swing.JCheckBox();
        PeternakanComboBox = new javax.swing.JComboBox<>();
        PerikananComboBox = new javax.swing.JComboBox<>();
        KehutananComboBox = new javax.swing.JComboBox<>();
        UsahaUtamaComboBox = new javax.swing.JComboBox<>();
        InsertButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 141, 169));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(229, 88, 7));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 329, -1));

        jPanel4.setBackground(new java.awt.Color(126, 23, 23));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 329, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo BPS 200.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(229, 88, 7));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSERT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 329, -1));

        jPanel6.setBackground(new java.awt.Color(229, 88, 7));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PROFILE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 329, -1));

        jPanel10.setBackground(new java.awt.Color(229, 88, 7));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DELETE");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 329, -1));

        jPanel7.setBackground(new java.awt.Color(229, 88, 7));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VIEW");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 329, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 88, 7));
        jButton1.setText("LOGOUT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 189, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        KIPPanel.setBackground(new java.awt.Color(236, 248, 249));
        KIPPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        KabKotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KabKotaLabel.setText("Kab/Kota");

        TahunLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TahunLabel.setText("Tahun");

        ProvinsiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProvinsiLabel.setText("Provinsi");

        KecamatanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KecamatanLabel.setText("Kecamatan");

        KodeKJULabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KodeKJULabel.setText("Kode KJU");

        NoUrutLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoUrutLabel.setText("No Urut Dalam Satu Kab/Kota");

        NamaPerusahaanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NamaPerusahaanLabel.setText("Nama Perusahaan Pertanian");

        AlamatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlamatLabel.setText("Alamat Perusahaan Pertanian");

        NoTelepoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoTelepoLabel.setText("No Telepon");

        NoFaxLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoFaxLabel.setText("No Fax");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        BentukBadanHukumLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BentukBadanHukumLabel.setText("Bentuk Badan Hukum");

        TahunTextField.setForeground(new java.awt.Color(204, 204, 204));
        TahunTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunTextFieldActionPerformed(evt);
            }
        });

        ProvinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));

        KabKotaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        KecamatanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AlamatTextArea.setColumns(20);
        AlamatTextArea.setRows(5);
        jScrollPane1.setViewportView(AlamatTextArea);

        BentukBadanHukumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perusahaan Negara (PN)", "Perusahaan Daerah (PD)", "Persero", "Perum", "Perseroan Terbatas" }));

        KIPJudulPanel.setBackground(new java.awt.Color(6, 141, 169));
        KIPJudulPanel.setPreferredSize(new java.awt.Dimension(650, 100));

        KIPJudulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KIPJudulLabel.setForeground(new java.awt.Color(255, 255, 255));
        KIPJudulLabel.setText("Kode Identitas Perusahaan (KIP)");

        javax.swing.GroupLayout KIPJudulPanelLayout = new javax.swing.GroupLayout(KIPJudulPanel);
        KIPJudulPanel.setLayout(KIPJudulPanelLayout);
        KIPJudulPanelLayout.setHorizontalGroup(
            KIPJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPJudulPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(KIPJudulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KIPJudulPanelLayout.setVerticalGroup(
            KIPJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPJudulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KIPJudulLabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        errorTahun.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorTahun.setForeground(new java.awt.Color(255, 0, 51));
        errorTahun.setText("Tidak boleh mengandung huruf!");

        errorKJU.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorKJU.setForeground(new java.awt.Color(255, 0, 0));
        errorKJU.setText("Tidak boleh mengandung huruf!");

        errorNoKabKot.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorNoKabKot.setForeground(new java.awt.Color(255, 0, 0));
        errorNoKabKot.setText("Tidak boleh mengandung huruf!");

        errorPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorPerusahaan.setForeground(new java.awt.Color(255, 0, 0));
        errorPerusahaan.setText("Tidak boleh mengandung huruf!");

        errorAlamat.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorAlamat.setForeground(new java.awt.Color(255, 0, 0));
        errorAlamat.setText("Tidak boleh mengandung huruf!");

        errorTelepon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorTelepon.setForeground(new java.awt.Color(255, 0, 0));
        errorTelepon.setText("Tidak boleh mengandung huruf!");

        errorFax.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorFax.setForeground(new java.awt.Color(255, 0, 0));
        errorFax.setText("Tidak boleh mengandung huruf!");

        errorEmail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorEmail.setForeground(new java.awt.Color(255, 0, 0));
        errorEmail.setText("Tidak boleh mengandung huruf!");

        javax.swing.GroupLayout KIPPanelLayout = new javax.swing.GroupLayout(KIPPanel);
        KIPPanel.setLayout(KIPPanelLayout);
        KIPPanelLayout.setHorizontalGroup(
            KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KIPJudulPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KIPPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KecamatanLabel)
                    .addComponent(TahunLabel)
                    .addComponent(ProvinsiLabel)
                    .addComponent(KabKotaLabel)
                    .addComponent(KodeKJULabel)
                    .addComponent(NoUrutLabel)
                    .addComponent(NamaPerusahaanLabel)
                    .addComponent(AlamatLabel)
                    .addComponent(NoTelepoLabel)
                    .addComponent(NoFaxLabel)
                    .addComponent(EmailLabel)
                    .addComponent(BentukBadanHukumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorEmail)
                    .addComponent(errorFax)
                    .addComponent(errorTelepon)
                    .addComponent(errorAlamat)
                    .addComponent(errorPerusahaan)
                    .addComponent(errorNoKabKot)
                    .addComponent(errorTahun)
                    .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TahunTextField)
                        .addComponent(ProvinsiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KabKotaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KecamatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NoUrutTextField)
                        .addComponent(NamaPerusahaanTextField)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(NoTeleponTextField)
                        .addComponent(NoFaxTextField)
                        .addComponent(EmailTextField)
                        .addComponent(BentukBadanHukumComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorKJU)
                        .addComponent(KodeKJUTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(47, 47, 47))
        );
        KIPPanelLayout.setVerticalGroup(
            KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPPanelLayout.createSequentialGroup()
                .addComponent(KIPJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunLabel)
                    .addComponent(TahunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTahun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KIPPanelLayout.createSequentialGroup()
                        .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProvinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinsiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KabKotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KabKotaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KecamatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KecamatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodeKJUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KodeKJULabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorKJU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoUrutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoUrutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorNoKabKot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPerusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaPerusahaanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPerusahaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoTelepoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTelepon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoFaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFaxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorFax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KIPPanelLayout.createSequentialGroup()
                        .addComponent(errorEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BentukBadanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BentukBadanHukumLabel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        DPPPanel.setBackground(new java.awt.Color(236, 248, 249));
        DPPPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        jPanel9.setBackground(new java.awt.Color(6, 141, 169));
        jPanel9.setPreferredSize(new java.awt.Dimension(650, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pencacahan dengan Kuesioner Rutin/DPP ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(98, 98, 98))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        StatusPerusahaanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusPerusahaanLabel.setText("Status Perusahan");

        StatusKunjunganLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusKunjunganLabel.setText("Status Kunjungan");

        SubsektorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubsektorLabel.setText("Subsektor");

        TanamanPanganLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TanamanPanganLabel.setText("Tanaman Pangan");

        HortikulturaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HortikulturaLabel.setText("Hortikultura");

        PerkebunanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PerkebunanLabel.setText("Perkebunan");

        PeternakanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PeternakanLabel.setText("Peternakan");

        KehutananLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KehutananLabel.setText("Kehutanan");

        PerikananLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PerikananLabel.setText("Perikanan");

        UsahaUtamaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsahaUtamaLabel.setText("Jenis Usaha Utama");

        StatuKunjunganBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah dikunjungi/mendapatkan informasi dari pihak lain(dinas,dll)", "Belum dikonfirmasi keberadaannya" }));

        StatusPerusahanBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tutup Sementara/Tidak Ada Kegiatan", "Belum Berproduksi", "Tidak Bersedia Diwawancarai", "Alih Usaha ke Non Pertanian", "Tutup", "Tidak Ditemukan", "Baru", "Ganda", " ", " " }));

        TanamanPanganComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));

        HortikulturaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));

        KakaoCokelatCheckBox.setText("3a-Kakao/Cokelat");

        KaretCheckBox.setText("3b-Karet");
        KaretCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaretCheckBoxActionPerformed(evt);
            }
        });

        KelapaSawitCheckBox.setText("3c-Kelapa Sawit");

        KopiCheckBox.setText("3d-Kopi");

        TehCheckBox.setText("3e-Teh");

        TebuCheckBox.setText("3f-Tebu");

        TembakauCheckBox.setText("3g-Tembakau");

        CengkehCheckBox.setText("3h-Cengkeh");
        CengkehCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CengkehCheckBoxActionPerformed(evt);
            }
        });

        KelapaCheckBox.setText("3i-Kelapa");

        LadaCheckBox.setText("3j-Lada");

        TanamanLainCheckBox.setText("3k-Tanaman Lain");
        TanamanLainCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanamanLainCheckBoxActionPerformed(evt);
            }
        });

        PeternakanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));

        PerikananComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tida Ada", "Ada" }));

        KehutananComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));

        UsahaUtamaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));

        InsertButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertButton.setForeground(new java.awt.Color(229, 88, 7));
        InsertButton.setText("Update");

        javax.swing.GroupLayout DPPPanelLayout = new javax.swing.GroupLayout(DPPPanel);
        DPPPanel.setLayout(DPPPanelLayout);
        DPPPanelLayout.setHorizontalGroup(
            DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPPPanelLayout.createSequentialGroup()
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DPPPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DPPPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(StatusPerusahaanLabel)
                                .addGap(164, 164, 164)
                                .addComponent(StatusPerusahanBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TanamanPanganLabel)
                                    .addComponent(PeternakanLabel)
                                    .addComponent(KehutananLabel)
                                    .addComponent(PerikananLabel)
                                    .addComponent(HortikulturaLabel)
                                    .addComponent(PerkebunanLabel)
                                    .addComponent(UsahaUtamaLabel))
                                .addGap(130, 130, 130)
                                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsahaUtamaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TanamanPanganComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HortikulturaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PerikananComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(KehutananComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(DPPPanelLayout.createSequentialGroup()
                                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(KaretCheckBox)
                                            .addComponent(KakaoCokelatCheckBox)
                                            .addComponent(KelapaSawitCheckBox)
                                            .addComponent(KopiCheckBox)
                                            .addComponent(TehCheckBox)
                                            .addComponent(TebuCheckBox))
                                        .addGap(18, 18, 18)
                                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CengkehCheckBox)
                                            .addComponent(TembakauCheckBox)
                                            .addComponent(KelapaCheckBox)
                                            .addComponent(LadaCheckBox)
                                            .addComponent(TanamanLainCheckBox))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(PeternakanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(SubsektorLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(StatusKunjunganLabel)
                                .addGap(164, 164, 164)
                                .addComponent(StatuKunjunganBox, 0, 1, Short.MAX_VALUE)))))
                .addGap(48, 48, 48))
        );
        DPPPanelLayout.setVerticalGroup(
            DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPPPanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusKunjunganLabel)
                    .addComponent(StatuKunjunganBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusPerusahanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusPerusahaanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubsektorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanamanPanganLabel)
                    .addComponent(TanamanPanganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HortikulturaLabel)
                    .addComponent(HortikulturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerkebunanLabel)
                    .addComponent(KakaoCokelatCheckBox)
                    .addComponent(TembakauCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KaretCheckBox)
                    .addComponent(CengkehCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelapaSawitCheckBox)
                    .addComponent(KelapaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KopiCheckBox)
                    .addComponent(LadaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TehCheckBox)
                    .addComponent(TanamanLainCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TebuCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeternakanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeternakanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KehutananLabel)
                    .addComponent(KehutananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerikananLabel)
                    .addComponent(PerikananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsahaUtamaLabel)
                    .addComponent(UsahaUtamaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertButton)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KIPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DPPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(KIPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DPPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(229, 88, 7));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMIN - UPDATE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel7)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TahunTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunTextFieldActionPerformed

    private void KaretCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaretCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KaretCheckBoxActionPerformed

    private void CengkehCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CengkehCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CengkehCheckBoxActionPerformed

    private void TanamanLainCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanamanLainCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanamanLainCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JTextArea AlamatTextArea;
    private javax.swing.JComboBox<String> BentukBadanHukumComboBox;
    private javax.swing.JLabel BentukBadanHukumLabel;
    private javax.swing.JCheckBox CengkehCheckBox;
    private javax.swing.JPanel DPPPanel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JComboBox<String> HortikulturaComboBox;
    private javax.swing.JLabel HortikulturaLabel;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel KIPJudulLabel;
    private javax.swing.JPanel KIPJudulPanel;
    private javax.swing.JPanel KIPPanel;
    private javax.swing.JComboBox<String> KabKotaComboBox;
    private javax.swing.JLabel KabKotaLabel;
    private javax.swing.JCheckBox KakaoCokelatCheckBox;
    private javax.swing.JCheckBox KaretCheckBox;
    private javax.swing.JComboBox<String> KecamatanComboBox;
    private javax.swing.JLabel KecamatanLabel;
    private javax.swing.JComboBox<String> KehutananComboBox;
    private javax.swing.JLabel KehutananLabel;
    private javax.swing.JCheckBox KelapaCheckBox;
    private javax.swing.JCheckBox KelapaSawitCheckBox;
    private javax.swing.JLabel KodeKJULabel;
    private javax.swing.JTextField KodeKJUTextField;
    private javax.swing.JCheckBox KopiCheckBox;
    private javax.swing.JCheckBox LadaCheckBox;
    private javax.swing.JLabel NamaPerusahaanLabel;
    private javax.swing.JTextField NamaPerusahaanTextField;
    private javax.swing.JLabel NoFaxLabel;
    private javax.swing.JTextField NoFaxTextField;
    private javax.swing.JLabel NoTelepoLabel;
    private javax.swing.JTextField NoTeleponTextField;
    private javax.swing.JLabel NoUrutLabel;
    private javax.swing.JTextField NoUrutTextField;
    private javax.swing.JComboBox<String> PerikananComboBox;
    private javax.swing.JLabel PerikananLabel;
    private javax.swing.JLabel PerkebunanLabel;
    private javax.swing.JComboBox<String> PeternakanComboBox;
    private javax.swing.JLabel PeternakanLabel;
    private javax.swing.JComboBox<String> ProvinsiComboBox;
    private javax.swing.JLabel ProvinsiLabel;
    private javax.swing.JComboBox<String> StatuKunjunganBox;
    private javax.swing.JLabel StatusKunjunganLabel;
    private javax.swing.JLabel StatusPerusahaanLabel;
    private javax.swing.JComboBox<String> StatusPerusahanBox;
    private javax.swing.JLabel SubsektorLabel;
    private javax.swing.JLabel TahunLabel;
    private javax.swing.JTextField TahunTextField;
    private javax.swing.JCheckBox TanamanLainCheckBox;
    private javax.swing.JComboBox<String> TanamanPanganComboBox;
    private javax.swing.JLabel TanamanPanganLabel;
    private javax.swing.JCheckBox TebuCheckBox;
    private javax.swing.JCheckBox TehCheckBox;
    private javax.swing.JCheckBox TembakauCheckBox;
    private javax.swing.JComboBox<String> UsahaUtamaComboBox;
    private javax.swing.JLabel UsahaUtamaLabel;
    private javax.swing.JLabel errorAlamat;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFax;
    private javax.swing.JLabel errorKJU;
    private javax.swing.JLabel errorNoKabKot;
    private javax.swing.JLabel errorPerusahaan;
    private javax.swing.JLabel errorTahun;
    private javax.swing.JLabel errorTelepon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
