/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import javax.swing.JCheckBox;
import keltujuhdpp.entity.Validasi;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamda
 */
public class AdminUpdate extends javax.swing.JFrame {
    private Connection conn;
//    private DefaultTableModel model;
    private PreparedStatement pstmt;
    private Statement stat;
    private ResultSet rs;
    private boolean validasi=true;
    private String id;
    
    /**
     * Creates new form ProfileAdmin
     */
    public AdminUpdate() {
        initComponents();
        conn=connection.getConnection();
        getProvinsi();
        System.out.println("masuk admin insert");
//        data();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        KIPPanel = new javax.swing.JPanel();
        KabKotaLabel = new javax.swing.JLabel();
        TahunLabel = new javax.swing.JLabel();
        ProvinsiLabel = new javax.swing.JLabel();
        KecamatanLabel = new javax.swing.JLabel();
        KodeKJULabel = new javax.swing.JLabel();
        NoUrutLabel = new javax.swing.JLabel();
        NamaPerusahaanLabel = new javax.swing.JLabel();
        AlamatLabel = new javax.swing.JLabel();
        NoTelepoLabel = new javax.swing.JLabel();
        NoFaxLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        BentukBadanHukumLabel = new javax.swing.JLabel();
        kodeKJUTextField = new javax.swing.JTextField();
        tahunTextField = new javax.swing.JTextField();
        provinsiComboBox = new javax.swing.JComboBox<>();
        kabKotComboBox = new javax.swing.JComboBox<>();
        kecamatanComboBox = new javax.swing.JComboBox<>();
        noUrutTextField = new javax.swing.JTextField();
        namaPerusahaanTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        noTeleponTextField = new javax.swing.JTextField();
        noFaxTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        bentukBadanHukumComboBox = new javax.swing.JComboBox<>();
        KIPJudulPanel = new javax.swing.JPanel();
        KIPJudulLabel = new javax.swing.JLabel();
        errorTahun = new javax.swing.JLabel();
        errorKJU = new javax.swing.JLabel();
        errorNoKabKot = new javax.swing.JLabel();
        errorPerusahaan = new javax.swing.JLabel();
        errorAlamat = new javax.swing.JLabel();
        errorTelepon = new javax.swing.JLabel();
        errorFax = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        space = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        space4 = new javax.swing.JLabel();
        space5 = new javax.swing.JLabel();
        DPPPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        StatusPerusahaanLabel = new javax.swing.JLabel();
        StatusKunjunganLabel = new javax.swing.JLabel();
        SubsektorLabel = new javax.swing.JLabel();
        TanamanPanganLabel = new javax.swing.JLabel();
        HortikulturaLabel = new javax.swing.JLabel();
        PerkebunanLabel = new javax.swing.JLabel();
        PeternakanLabel = new javax.swing.JLabel();
        KehutananLabel = new javax.swing.JLabel();
        PerikananLabel = new javax.swing.JLabel();
        UsahaUtamaLabel = new javax.swing.JLabel();
        statusKunjunganComboBox = new javax.swing.JComboBox<>();
        statusPerusahaanComboBox = new javax.swing.JComboBox<>();
        tanamanPanganComboBox = new javax.swing.JComboBox<>();
        hortikulturaComboBox = new javax.swing.JComboBox<>();
        aCheckBox = new javax.swing.JCheckBox();
        bCheckBox = new javax.swing.JCheckBox();
        cCheckBox = new javax.swing.JCheckBox();
        dCheckBox = new javax.swing.JCheckBox();
        eCheckBox = new javax.swing.JCheckBox();
        fCheckBox = new javax.swing.JCheckBox();
        gCheckBox = new javax.swing.JCheckBox();
        hCheckBox = new javax.swing.JCheckBox();
        iCheckBox = new javax.swing.JCheckBox();
        jCheckBox = new javax.swing.JCheckBox();
        kCheckBox = new javax.swing.JCheckBox();
        peternakanComboBox = new javax.swing.JComboBox<>();
        perikananComboBox = new javax.swing.JComboBox<>();
        kehutananComboBox = new javax.swing.JComboBox<>();
        usahaUtamaComboBox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 141, 169));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(229, 88, 7));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 329, -1));

        jPanel4.setBackground(new java.awt.Color(229, 88, 7));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFILE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 329, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo BPS 200.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(126, 23, 23));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSERT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 329, -1));

        jPanel6.setBackground(new java.awt.Color(229, 88, 7));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UPDATE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 329, -1));

        jPanel10.setBackground(new java.awt.Color(229, 88, 7));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DELETE");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 329, -1));

        jPanel7.setBackground(new java.awt.Color(229, 88, 7));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VIEW");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 329, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 88, 7));
        jButton1.setText("LOGOUT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 189, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        KIPPanel.setBackground(new java.awt.Color(236, 248, 249));
        KIPPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        KabKotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KabKotaLabel.setText("Kab/Kota");

        TahunLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TahunLabel.setText("Tahun");

        ProvinsiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProvinsiLabel.setText("Provinsi");

        KecamatanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KecamatanLabel.setText("Kecamatan");

        KodeKJULabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KodeKJULabel.setText("Kode KJU");

        NoUrutLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoUrutLabel.setText("No Urut Dalam Satu Kab/Kota");

        NamaPerusahaanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NamaPerusahaanLabel.setText("Nama Perusahaan Pertanian");

        AlamatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlamatLabel.setText("Alamat Perusahaan Pertanian");

        NoTelepoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoTelepoLabel.setText("No Telepon");

        NoFaxLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoFaxLabel.setText("No Fax");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        BentukBadanHukumLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BentukBadanHukumLabel.setText("Bentuk Badan Hukum");

        tahunTextField.setForeground(new java.awt.Color(204, 204, 204));
        tahunTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunTextFieldActionPerformed(evt);
            }
        });

        provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        provinsiComboBox.setSelectedIndex(-1);
        provinsiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiComboBoxActionPerformed(evt);
            }
        });

        kabKotComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabKotComboBoxActionPerformed(evt);
            }
        });

        kecamatanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        kecamatanComboBox.setSelectedIndex(-1);

        noUrutTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noUrutTextFieldKeyReleased(evt);
            }
        });

        namaPerusahaanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaPerusahaanTextFieldKeyReleased(evt);
            }
        });

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        alamatTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alamatTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(alamatTextArea);

        noTeleponTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noTeleponTextFieldKeyReleased(evt);
            }
        });

        noFaxTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noFaxTextFieldKeyReleased(evt);
            }
        });

        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });

        bentukBadanHukumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perusahaan Negara (PN)", "Perusahaan Daerah (PD)", "Persero", "Perum", "Perseroan Terbatas" }));
        bentukBadanHukumComboBox.setSelectedIndex(-1);

        KIPJudulPanel.setBackground(new java.awt.Color(6, 141, 169));
        KIPJudulPanel.setPreferredSize(new java.awt.Dimension(650, 100));

        KIPJudulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        KIPJudulLabel.setForeground(new java.awt.Color(255, 255, 255));
        KIPJudulLabel.setText("Kode Identitas Perusahaan (KIP)");

        javax.swing.GroupLayout KIPJudulPanelLayout = new javax.swing.GroupLayout(KIPJudulPanel);
        KIPJudulPanel.setLayout(KIPJudulPanelLayout);
        KIPJudulPanelLayout.setHorizontalGroup(
            KIPJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPJudulPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(KIPJudulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KIPJudulPanelLayout.setVerticalGroup(
            KIPJudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPJudulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KIPJudulLabel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        errorTahun.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorTahun.setForeground(new java.awt.Color(255, 0, 51));
        errorTahun.setText("Tidak boleh mengandung huruf!");
        errorTahun.setVisible(false);

        errorKJU.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorKJU.setForeground(new java.awt.Color(255, 0, 0));
        errorKJU.setText("Kode KJU harus berupa angka");
        errorKJU.setVisible(false);

        errorNoKabKot.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorNoKabKot.setForeground(new java.awt.Color(255, 0, 0));
        errorNoKabKot.setText("No urut harus berupa angka ");
        errorNoKabKot.setVisible(false);

        errorPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorPerusahaan.setForeground(new java.awt.Color(255, 0, 0));
        errorPerusahaan.setText("Alamat hanya berupa angka dan huruf");
        errorPerusahaan.setVisible(false);

        errorAlamat.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorAlamat.setForeground(new java.awt.Color(255, 0, 0));
        errorAlamat.setText("Alamat hanya berupa huruf, angka, dan karakter khusus");
        errorAlamat.setVisible(false);

        errorTelepon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorTelepon.setForeground(new java.awt.Color(255, 0, 0));
        errorTelepon.setText("Nomor Telepon hanya berupa angka dan karakter +");
        errorTelepon.setVisible(false);

        errorFax.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorFax.setForeground(new java.awt.Color(255, 0, 0));
        errorFax.setText("Nomor Fax hanya berupa angka dan karakter + - ");
        errorFax.setVisible(false);

        errorEmail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        errorEmail.setForeground(new java.awt.Color(255, 0, 0));
        errorEmail.setText("Data yang diinputkan harus berupa email");
        errorEmail.setVisible(false);

        space.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space.setForeground(new java.awt.Color(255, 0, 0));
        space.setText(" ");
        errorNoKabKot.setVisible(false);

        space1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space1.setForeground(new java.awt.Color(255, 0, 0));
        space1.setText(" ");
        errorNoKabKot.setVisible(false);

        space2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space2.setForeground(new java.awt.Color(255, 0, 0));
        space2.setText(" ");
        errorNoKabKot.setVisible(false);

        space3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space3.setForeground(new java.awt.Color(255, 0, 0));
        space3.setText(" ");
        errorNoKabKot.setVisible(false);

        space4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space4.setForeground(new java.awt.Color(255, 0, 0));
        space4.setText(" ");
        errorNoKabKot.setVisible(false);

        space5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        space5.setForeground(new java.awt.Color(255, 0, 0));
        space5.setText(" ");
        errorNoKabKot.setVisible(false);

        javax.swing.GroupLayout KIPPanelLayout = new javax.swing.GroupLayout(KIPPanel);
        KIPPanel.setLayout(KIPPanelLayout);
        KIPPanelLayout.setHorizontalGroup(
            KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KIPJudulPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KIPPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KecamatanLabel)
                    .addComponent(TahunLabel)
                    .addComponent(ProvinsiLabel)
                    .addComponent(KabKotaLabel)
                    .addComponent(KodeKJULabel)
                    .addComponent(NoUrutLabel)
                    .addComponent(NamaPerusahaanLabel)
                    .addComponent(AlamatLabel)
                    .addComponent(NoTelepoLabel)
                    .addComponent(NoFaxLabel)
                    .addComponent(EmailLabel)
                    .addComponent(BentukBadanHukumLabel)
                    .addComponent(space)
                    .addComponent(space1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorEmail)
                    .addComponent(errorFax)
                    .addComponent(errorTelepon)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KIPPanelLayout.createSequentialGroup()
                        .addComponent(errorAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(space5))
                    .addComponent(errorPerusahaan)
                    .addComponent(errorNoKabKot)
                    .addComponent(errorTahun)
                    .addComponent(tahunTextField)
                    .addComponent(provinsiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kabKotComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kecamatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noUrutTextField)
                    .addComponent(namaPerusahaanTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(noTeleponTextField)
                    .addComponent(noFaxTextField)
                    .addComponent(emailTextField)
                    .addComponent(bentukBadanHukumComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorKJU)
                    .addComponent(kodeKJUTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
        );
        KIPPanelLayout.setVerticalGroup(
            KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPPanelLayout.createSequentialGroup()
                .addComponent(KIPJudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunLabel)
                    .addComponent(tahunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTahun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KIPPanelLayout.createSequentialGroup()
                        .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinsiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kabKotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KabKotaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kecamatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KecamatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeKJUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KodeKJULabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorKJU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noUrutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoUrutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorNoKabKot)
                    .addComponent(space))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPerusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaPerusahaanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorPerusahaan)
                    .addComponent(space1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorAlamat)
                    .addComponent(space5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoTelepoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorTelepon)
                    .addComponent(space2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noFaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFaxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorFax)
                    .addComponent(space3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KIPPanelLayout.createSequentialGroup()
                        .addGroup(KIPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(errorEmail)
                            .addComponent(space4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bentukBadanHukumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BentukBadanHukumLabel))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        DPPPanel.setBackground(new java.awt.Color(236, 248, 249));
        DPPPanel.setPreferredSize(new java.awt.Dimension(650, 700));

        jPanel9.setBackground(new java.awt.Color(6, 141, 169));
        jPanel9.setPreferredSize(new java.awt.Dimension(650, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pencacahan dengan Kuesioner Rutin/DPP ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(98, 98, 98))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        StatusPerusahaanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusPerusahaanLabel.setText("Status Perusahan");

        StatusKunjunganLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusKunjunganLabel.setText("Status Kunjungan");

        SubsektorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubsektorLabel.setText("Subsektor");

        TanamanPanganLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TanamanPanganLabel.setText("Tanaman Pangan");

        HortikulturaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HortikulturaLabel.setText("Hortikultura");

        PerkebunanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PerkebunanLabel.setText("Perkebunan");

        PeternakanLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PeternakanLabel.setText("Peternakan");

        KehutananLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KehutananLabel.setText("Kehutanan");

        PerikananLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PerikananLabel.setText("Perikanan");

        UsahaUtamaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsahaUtamaLabel.setText("Jenis Usaha Utama");

        statusKunjunganComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah dikunjungi/mendapatkan informasi dari pihak lain(dinas,dll)", "Belum dikonfirmasi keberadaannya" }));
        statusKunjunganComboBox.setSelectedIndex(-1);

        statusPerusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tutup Sementara/Tidak Ada Kegiatan", "Belum Berproduksi", "Tidak Bersedia Diwawancarai", "Alih Usaha ke Non Pertanian", "Tutup", "Tidak Ditemukan", "Baru", "Ganda", " ", " " }));
        statusPerusahaanComboBox.setSelectedIndex(-1);

        tanamanPanganComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));
        tanamanPanganComboBox.setSelectedIndex(-1);

        hortikulturaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));
        hortikulturaComboBox.setSelectedIndex(-1);

        aCheckBox.setText("3a-Kakao/Cokelat");

        bCheckBox.setText("3b-Karet");
        bCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckBoxActionPerformed(evt);
            }
        });

        cCheckBox.setText("3c-Kelapa Sawit");

        dCheckBox.setText("3d-Kopi");

        eCheckBox.setText("3e-Teh");

        fCheckBox.setText("3f-Tebu");

        gCheckBox.setText("3g-Tembakau");

        hCheckBox.setText("3h-Cengkeh");
        hCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hCheckBoxActionPerformed(evt);
            }
        });

        iCheckBox.setText("3i-Kelapa");

        jCheckBox.setText("3j-Lada");

        kCheckBox.setText("3k-Tanaman Lain");
        kCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kCheckBoxActionPerformed(evt);
            }
        });

        peternakanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));
        peternakanComboBox.setSelectedIndex(-1);

        perikananComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tida Ada", "Ada" }));
        perikananComboBox.setSelectedIndex(-1);

        kehutananComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Ada" }));
        kehutananComboBox.setSelectedIndex(-1);

        usahaUtamaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.  Padi/palawija", "2. Hortikultura", "3a. Perkebunan Kakao/cokelat", "3b. Perkebunan Karet", "3c. Perkebunan Kelapa Sawit", "3d. Perkebunan Kopi", "3e. Perkebunan Teh ", "3f. Perkebunan Tebu", "3g. Perkebunan Tembakau ", "3h. Perkebunan Cengkeh", "3i Perkebunan Kelapa ", "3j. Perkebunan Lada", "3k. Tanaman Perkebunan Lainnya", "4. HPH/IUPHHK-HA", "5. HPHT/IUPHHK-HT/Perhutani/Kehutanan lainnya", "6. Penangkaran STL", "7a. Budidaya Udang ", "7b. Budidaya Bandeng", "7c. Budidaya Ikan lainnya  di Laut", "7d. Budidaya ikan di laut  ", "7e.  Budidaya Ikan di Air Tawar", "7f. Budidaya Pembenihan", "8. Penangkapan Ikan", "9. Ternak Sapi Perah", "10. Ternak Besar/Kecil", "11. Unggas", " ", " " }));
        usahaUtamaComboBox.setSelectedIndex(-1);

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(229, 88, 7));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(229, 88, 7));
        hapusButton.setText("Hapus Data");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DPPPanelLayout = new javax.swing.GroupLayout(DPPPanel);
        DPPPanel.setLayout(DPPPanelLayout);
        DPPPanelLayout.setHorizontalGroup(
            DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPPPanelLayout.createSequentialGroup()
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DPPPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DPPPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TanamanPanganLabel)
                                    .addComponent(PeternakanLabel)
                                    .addComponent(KehutananLabel)
                                    .addComponent(PerikananLabel)
                                    .addComponent(HortikulturaLabel)
                                    .addComponent(PerkebunanLabel)
                                    .addComponent(UsahaUtamaLabel))
                                .addGap(130, 130, 130)
                                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usahaUtamaComboBox, 0, 1, Short.MAX_VALUE)
                                    .addComponent(tanamanPanganComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hortikulturaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(perikananComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kehutananComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(DPPPanelLayout.createSequentialGroup()
                                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bCheckBox)
                                            .addComponent(aCheckBox)
                                            .addComponent(cCheckBox)
                                            .addComponent(dCheckBox)
                                            .addComponent(eCheckBox)
                                            .addComponent(fCheckBox))
                                        .addGap(18, 18, 18)
                                        .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hCheckBox)
                                            .addComponent(gCheckBox)
                                            .addComponent(iCheckBox)
                                            .addComponent(jCheckBox)
                                            .addComponent(kCheckBox))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(peternakanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(StatusKunjunganLabel)
                                .addGap(164, 164, 164)
                                .addComponent(statusKunjunganComboBox, 0, 1, Short.MAX_VALUE))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(SubsektorLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(DPPPanelLayout.createSequentialGroup()
                                .addComponent(StatusPerusahaanLabel)
                                .addGap(166, 166, 166)
                                .addComponent(statusPerusahaanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(48, 48, 48))
        );
        DPPPanelLayout.setVerticalGroup(
            DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPPPanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusKunjunganLabel)
                    .addComponent(statusKunjunganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPerusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusPerusahaanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubsektorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanamanPanganLabel)
                    .addComponent(tanamanPanganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HortikulturaLabel)
                    .addComponent(hortikulturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerkebunanLabel)
                    .addComponent(aCheckBox)
                    .addComponent(gCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCheckBox)
                    .addComponent(hCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCheckBox)
                    .addComponent(iCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dCheckBox)
                    .addComponent(jCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCheckBox)
                    .addComponent(kCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peternakanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeternakanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KehutananLabel)
                    .addComponent(kehutananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerikananLabel)
                    .addComponent(perikananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsahaUtamaLabel)
                    .addComponent(usahaUtamaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(DPPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(hapusButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KIPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DPPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(KIPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DPPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(229, 88, 7));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMIN - UPDATE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel7)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahunTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunTextFieldActionPerformed

    private void bCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCheckBoxActionPerformed

    private void hCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hCheckBoxActionPerformed

    private void kCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kCheckBoxActionPerformed

    private void provinsiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiComboBoxActionPerformed
        
        getKabKot();
//        kabKotComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_provinsiComboBoxActionPerformed

    private void kabKotComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabKotComboBoxActionPerformed
        getKecamatan();
//        kecamatanComboBox.setSelectedIndex(-1);
    }//GEN-LAST:event_kabKotComboBoxActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (!ValidasiNull()){
            JOptionPane.showMessageDialog(null, "Semua input harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }  
        if (ValidasiInput()==true) { 
            try {
                String tahun = tahunTextField.getText();
                String selectedItem = (String) provinsiComboBox.getSelectedItem();
                String provinsi = selectedItem.substring(0, 2);
                selectedItem = (String) kabKotComboBox.getSelectedItem();
                String kabKot = selectedItem.substring(0, 4);
                selectedItem = (String) kecamatanComboBox.getSelectedItem();
                String kecamatan = selectedItem.substring(0, 7);
                String kode_kju = kodeKJUTextField.getText();
                String no_urut = noUrutTextField.getText();
                String nama = namaPerusahaanTextField.getText();
                String alamat = alamatTextArea.getText();
                String no_telp = noTeleponTextField.getText();
                String no_fax = noFaxTextField.getText();
                String email = emailTextField.getText();
                int kode = bentukBadanHukumComboBox.getSelectedIndex() + 1;
                String badanHukum = "" + kode;
                kode = statusKunjunganComboBox.getSelectedIndex();
                String statusKunjungan = "" + kode;
                kode = statusPerusahaanComboBox.getSelectedIndex() + 1;
                String statusPerusahaan = "" + kode;
                kode = tanamanPanganComboBox.getSelectedIndex();
                String tanamanPangan = "" + kode;
                kode = hortikulturaComboBox.getSelectedIndex();
                String hortikultura = "" + kode;

                JCheckBox[] checkboxes = { aCheckBox, bCheckBox, cCheckBox, dCheckBox, eCheckBox, fCheckBox, gCheckBox, hCheckBox, iCheckBox, jCheckBox, kCheckBox };

                String perkebunan = "";
                for (int i = 0; i < checkboxes.length; i++) {
                    if (checkboxes[i].isSelected()) {
                        if (!perkebunan.isEmpty()) {
                            perkebunan += ",";
                        }
                        perkebunan += "3" + (char) ('a' + i);
                    }
                }
                kode = peternakanComboBox.getSelectedIndex();
                String peternakan = "" + kode;
                kode = kehutananComboBox.getSelectedIndex();
                String kehutanan = "" + kode;
                kode = perikananComboBox.getSelectedIndex();
                String perikanan = "" + kode;
                kode = usahaUtamaComboBox.getSelectedIndex() + 1;
                String usahaUtama = "" + kode;

                String myQuery = "UPDATE `perusahaan` SET `tahun`=?, `provinsi`=?, "
                        + "`kab_kot`=?, `kec`=?, `kode_kju`=?, `no_urut`=?, `nama`=?, "
                        + "`alamat`=?, `no_telp`=?, `no_fak`=?, `badan_hukum`=?, "
                        + "`sudah_dikunjungi`=?, `status`=?, `ada_tanaman_pangan`=?, "
                        + "`ada_hortikultura`=?, `perkebunan`=?, `ada_peternakan`=?, `ada_kehutanan`=?, "
                        + "`ada_perikanan`=?, `jenis_usaha`=? WHERE `id`=?";
                
                pstmt = conn.prepareStatement(myQuery);
                pstmt.setString(1, tahun);
                pstmt.setString(2, provinsi);
                pstmt.setString(3, kabKot);
                pstmt.setString(4, kecamatan);
                pstmt.setString(5, kode_kju);
                pstmt.setString(6, no_urut);
                pstmt.setString(7, nama);
                pstmt.setString(8, alamat);
                pstmt.setString(9, no_telp);
                pstmt.setString(10, no_fax);
                pstmt.setString(11, badanHukum);
                pstmt.setString(12, statusKunjungan);
                pstmt.setString(13, statusPerusahaan);
                pstmt.setString(14, tanamanPangan);
                pstmt.setString(15, hortikultura);
                pstmt.setString(16, perkebunan);
                pstmt.setString(17, peternakan);
                pstmt.setString(18, kehutanan);
                pstmt.setString(19, perikanan);
                pstmt.setString(20, usahaUtama);
                pstmt.setString(21, id); // Set nilai parameter id
                pstmt.executeUpdate();


                hapus();

                pstmt.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Data yang anda Inputkan Belum Sesuai!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void hapus(){
            provinsiComboBox.setSelectedIndex(-1);
            kabKotComboBox.setSelectedIndex(-1);
            kecamatanComboBox.setSelectedIndex(-1);
            kodeKJUTextField.setText("");
            noUrutTextField.setText("");
            namaPerusahaanTextField.setText("");
            alamatTextArea.setText("");
            noTeleponTextField.setText("");
            noFaxTextField.setText("");
            emailTextField.setText(""); 
            bentukBadanHukumComboBox.setSelectedIndex(-1);
            statusKunjunganComboBox.setSelectedIndex(-1);
            statusPerusahaanComboBox.setSelectedIndex(-1);
            tanamanPanganComboBox.setSelectedIndex(-1);
            hortikulturaComboBox.setSelectedIndex(-1);
            
            JCheckBox[] checkboxes = { aCheckBox, bCheckBox, cCheckBox, dCheckBox, eCheckBox, fCheckBox, gCheckBox, hCheckBox, iCheckBox, jCheckBox, kCheckBox };
               
            String perkebunan = "";
            for (int i = 0; i < checkboxes.length; i++) {
                checkboxes[i].setSelected(false) ;
            }
            peternakanComboBox.setSelectedIndex(-1);
            kehutananComboBox.setSelectedIndex(-1);
            perikananComboBox.setSelectedIndex(-1);
            usahaUtamaComboBox.setSelectedIndex(-1);
         
    }
    private void noUrutTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noUrutTextFieldKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_noUrutTextFieldKeyReleased

    private void namaPerusahaanTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPerusahaanTextFieldKeyReleased
        // TODO add your handling code here:
        if(Validasi.cekNamaPerusahaan(namaPerusahaanTextField.getText())==false){
           errorPerusahaan.setVisible(true);
           validasi=false;
       }else{
            errorPerusahaan.setVisible(false);
            validasi=true;
       }
    }//GEN-LAST:event_namaPerusahaanTextFieldKeyReleased

    private void alamatTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatTextAreaKeyReleased
        // TODO add your handling code here:
           if(Validasi.cekAlamatPerusahaan(alamatTextArea.getText())==false){
                errorAlamat.setVisible(true);
                validasi=false;
           }
           else{
               errorAlamat.setVisible(false);
               validasi=true;
           }
    }//GEN-LAST:event_alamatTextAreaKeyReleased

    private void noTeleponTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTeleponTextFieldKeyReleased
        // TODO add your handling code here:
        if(Validasi.cekNoTelepon(noTeleponTextField.getText())==false){
           errorTelepon.setVisible(true);
           validasi=false;
       }else{
           errorTelepon.setVisible(false);
           validasi=true;
       }
    }//GEN-LAST:event_noTeleponTextFieldKeyReleased

    private void noFaxTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noFaxTextFieldKeyReleased
        // TODO add your handling code here:
        if(Validasi.cekFaksimili(noFaxTextField.getText())==false){
           errorFax.setVisible(true);
           validasi=false;
       }else{
            errorFax.setVisible(false);
            validasi=true;
       }
    }//GEN-LAST:event_noFaxTextFieldKeyReleased

    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
        // TODO add your handling code here:
        if(Validasi.cekEmail(emailTextField.getText())==false){
           errorEmail.setVisible(true);
           validasi=false;
       } else{
            errorEmail.setVisible(false);
            validasi=true;
        }
    }//GEN-LAST:event_emailTextFieldKeyReleased

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void getTahun(){
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        tahunTextField.setText(String.valueOf(currentYear));
        tahunTextField.setEditable(false);
    }
    
    public Boolean ValidasiInput(){
        if(Validasi.cekKodeKJU(kodeKJUTextField.getText())==false){
            return false;
        }
        if(Validasi.cekNoUrut(noUrutTextField.getText())==false){
            return false;
        }
        if(Validasi.cekNamaPerusahaan(namaPerusahaanTextField.getText())==false){
            return false;
        }
        if(Validasi.cekAlamatPerusahaan(alamatTextArea.getText())==false){
           return false;
       }
        if(Validasi.cekNoTelepon(noTeleponTextField.getText())==false){
           return false;
       }
        if(Validasi.cekFaksimili(noFaxTextField.getText())==false){
           return false;
       }
        if(Validasi.cekEmail(emailTextField.getText())==false){
           return false;
       } 
        return true;
    }
    
    public Boolean ValidasiNull() {
        if (provinsiComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (kabKotComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (kecamatanComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (kodeKJUTextField.getText().isEmpty()) {
            return false;
        }
        if (namaPerusahaanTextField.getText().isEmpty()) {
            return false;
        }
        if (alamatTextArea.getText().isEmpty()) {
            return false;
        }
        if (noTeleponTextField.getText().isEmpty()) {
            return false;
        }
        if (noFaxTextField.getText().isEmpty()) {
            return false;
        }
        if (emailTextField.getText().isEmpty()) {
            return false;
        }
        if (bentukBadanHukumComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (statusKunjunganComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (statusPerusahaanComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (tanamanPanganComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (hortikulturaComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (peternakanComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (kehutananComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (perikananComboBox.getSelectedIndex() == -1) {
            return false;
        }
        if (usahaUtamaComboBox.getSelectedIndex() == -1) {
            return false;
        }
        return true;
    }

    
    private void getKecamatan() {
        if(kabKotComboBox.getSelectedItem()!=null){

        String selectedItem = (String) kabKotComboBox.getSelectedItem();
        String selectedKabKot = selectedItem.substring(0, 4) + "%";

        kecamatanComboBox.removeAllItems();

        // Mengambil data kabupaten/kota berdasarkan provinsi yang dipilih
        try {
            String myQuery = "SELECT kode_bps,nama_bps FROM m_kecamatan WHERE kode_bps LIKE ? ";
            pstmt = conn.prepareStatement(myQuery);
            pstmt.setString(1, selectedKabKot);
            ResultSet rs = pstmt.executeQuery();

            // Menambahkan data kabupaten/kota ke dalam JComboBox kabupaten
            while (rs.next()) {
                String namaKecamatan = rs.getString("nama_bps");
                String kodeKecamatan = rs.getString("kode_bps");
                kecamatanComboBox.addItem(kodeKecamatan+"-"+namaKecamatan);
            }

            rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
    }
    
    
    private void getKabKot() {
        // Mendapatkan provinsi yang dipilih
        if(provinsiComboBox.getSelectedItem()!=null){
        String selectedItem = (String) provinsiComboBox.getSelectedItem();
        String selectedProvinsi = selectedItem.substring(0, 2) + "%";


        // Menghapus item sebelumnya dari JComboBox kabupaten
        kabKotComboBox.removeAllItems();

        // Mengambil data kabupaten/kota berdasarkan provinsi yang dipilih
        try {
            String myQuery = "SELECT nama_dagri, kode_bps FROM m_kabupaten WHERE kode_bps LIKE ?";
            pstmt = conn.prepareStatement(myQuery);
            pstmt.setString(1, selectedProvinsi);
            ResultSet rs = pstmt.executeQuery();

            // Menambahkan data kabupaten/kota ke dalam JComboBox kabupaten
            while (rs.next()) {
                String namaKabupaten = rs.getString("nama_dagri");
                String kodeKabupaten = rs.getString("kode_bps");
                kabKotComboBox.addItem(kodeKabupaten + " - " + namaKabupaten);
            }

            rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
    }
    
    private void getProvinsi() {
    try {
        String myQuery = "SELECT * FROM m_provinsi ORDER BY nama_bps";
        pstmt = conn.prepareStatement(myQuery);
        ResultSet rs = pstmt.executeQuery();

        ArrayList<String> provinsiList = new ArrayList<>();
        while (rs.next()) {
            String kodeProv = rs.getString("kode_bps");
            String namaProvinsi = rs.getString("nama_bps");
            provinsiList.add(kodeProv + " - " + namaProvinsi);
        }

        // Mengganti model JComboBox provinsiComboBox dengan data provinsi yang baru
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(provinsiList.toArray(new String[0]));
        provinsiComboBox.setModel(comboBoxModel);
        provinsiComboBox.setSelectedIndex(-1);

    } catch (SQLException e) {
        e.printStackTrace();
    } 

}
    
    public void data(String id) {
    try {
    
        String myQuery = "SELECT * FROM perusahaan WHERE id=?";
        PreparedStatement pstmt = conn.prepareStatement(myQuery);
        pstmt.setString(1, id);
        System.out.println("id:"+id);
        this.id=id;
        ResultSet rs = pstmt.executeQuery();
        System.out.println("masuk data");
        JCheckBox[] checkboxes = { aCheckBox, bCheckBox, cCheckBox, dCheckBox, eCheckBox, fCheckBox, gCheckBox, hCheckBox, iCheckBox, jCheckBox, kCheckBox };
        if(rs.next()){
        tahunTextField.setText(rs.getString("tahun"));
            System.out.println(rs.getString("tahun"));
        for (int i = 0; i < provinsiComboBox.getItemCount(); i++) {
            String comboBoxItem = provinsiComboBox.getItemAt(i).toString();
            if (comboBoxItem.startsWith(rs.getString("provinsi"))) {
                provinsiComboBox.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < kabKotComboBox.getItemCount(); i++) {
            String comboBoxItem = kabKotComboBox.getItemAt(i).toString();
            if (comboBoxItem.startsWith(rs.getString("kab_kot"))) {
                kabKotComboBox.setSelectedIndex(i);
                break;
            }
        }

        for (int i = 0; i < kecamatanComboBox.getItemCount(); i++) {
            String comboBoxItem = kecamatanComboBox.getItemAt(i).toString();
            if (comboBoxItem.startsWith(rs.getString("kec"))) {
                kecamatanComboBox.setSelectedIndex(i);
                break;
            }
        }
        
        kodeKJUTextField.setText(rs.getString("kode_kju"));
        noUrutTextField.setText(rs.getString("no_urut"));
        namaPerusahaanTextField.setText(rs.getString("nama"));
        alamatTextArea.setText(rs.getString("alamat"));
        noTeleponTextField.setText(rs.getString("no_telp"));
        noFaxTextField.setText(rs.getString("no_fak"));
//        emailTextField.setText(rs.getString("email"));
        bentukBadanHukumComboBox.setSelectedIndex(Integer.parseInt(rs.getString("badan_hukum"))-1);
        statusKunjunganComboBox.setSelectedIndex(Integer.parseInt(rs.getString("sudah_dikunjungi")));
        statusPerusahaanComboBox.setSelectedIndex(Integer.parseInt(rs.getString("status"))-1);
        tanamanPanganComboBox.setSelectedIndex(Integer.parseInt(rs.getString("ada_tanaman_pangan")));
        hortikulturaComboBox.setSelectedIndex(Integer.parseInt(rs.getString("ada_hortikultura")));
        peternakanComboBox.setSelectedIndex(Integer.parseInt(rs.getString("ada_peternakan")));
        kehutananComboBox.setSelectedIndex(Integer.parseInt(rs.getString("ada_kehutanan")));
        perikananComboBox.setSelectedIndex(Integer.parseInt(rs.getString("ada_perikanan")));
        usahaUtamaComboBox.setSelectedIndex(Integer.parseInt(rs.getString("jenis_usaha"))-1);
    
                String[] perkebunanArray = rs.getString("perkebunan").split(",");

                // Memeriksa setiap item pada JComboBox
                for (String item : perkebunanArray) {
                    // Mengambil karakter setelah angka 3
                    char checkboxChar = item.charAt(1);

                    // Mengubah karakter menjadi indeks untuk checkboxes
                    int checkboxIndex = checkboxChar - 'a';

                    // Memeriksa checkbox yang sesuai
                    if (checkboxIndex >= 0 && checkboxIndex < checkboxes.length) {
                        checkboxes[checkboxIndex].setSelected(true);
                    }
                }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

}

public void transferID(String id){
    this.id=id;
    System.out.println("id:"+id);
}
//public void transfer(int id, String tahun, String prov, String kab, String kec, String kju, String no, String nama,
//        String alamat, String no_telp, String no_fax, String email, String badanHukum, String statusKunjungan,
//        String statusPerusahaan, String tanamanPangan, String hortikultura , String perkebunan,
//        String peternakan,  String kehutanan, String perikanan, String usahaUtama) {
//    
//    
//        JCheckBox[] checkboxes = { aCheckBox, bCheckBox, cCheckBox, dCheckBox, eCheckBox, fCheckBox, gCheckBox, hCheckBox, iCheckBox, jCheckBox, kCheckBox };
//        tahunTextField.setText(tahun);
//        
//        for (int i = 0; i < provinsiComboBox.getItemCount(); i++) {
//            String comboBoxItem = provinsiComboBox.getItemAt(i).toString();
//            if (comboBoxItem.startsWith(prov)) {
//                provinsiComboBox.setSelectedIndex(i);
//                break;
//            }
//        }
//        for (int i = 0; i < kabKotComboBox.getItemCount(); i++) {
//            String comboBoxItem = kabKotComboBox.getItemAt(i).toString();
//            if (comboBoxItem.startsWith(kab)) {
//                kabKotComboBox.setSelectedIndex(i);
//                break;
//            }
//        }
//
//        for (int i = 0; i < kecamatanComboBox.getItemCount(); i++) {
//            String comboBoxItem = kecamatanComboBox.getItemAt(i).toString();
//            if (comboBoxItem.startsWith(kec)) {
//                kecamatanComboBox.setSelectedIndex(i);
//                break;
//            }
//        }
//        
//        kodeKJUTextField.setText(kju);
//        noUrutTextField.setText(no);
//        namaPerusahaanTextField.setText(nama);
//        alamatTextArea.setText(alamat);
//        noTeleponTextField.setText(no_telp);
//        noFaxTextField.setText(no_fax);
//        emailTextField.setText(email);
//        bentukBadanHukumComboBox.setSelectedIndex(Integer.parseInt(badanHukum)-1);
//        statusKunjunganComboBox.setSelectedIndex(Integer.parseInt(statusKunjungan));
//        statusPerusahaanComboBox.setSelectedIndex(Integer.parseInt(statusPerusahaan)-1);
//        tanamanPanganComboBox.setSelectedIndex(Integer.parseInt(tanamanPangan));
//        hortikulturaComboBox.setSelectedIndex(Integer.parseInt(hortikultura));
//        peternakanComboBox.setSelectedIndex(Integer.parseInt(peternakan));
//        kehutananComboBox.setSelectedIndex(Integer.parseInt(kehutanan));
//        perikananComboBox.setSelectedIndex(Integer.parseInt(perikanan));
//        usahaUtamaComboBox.setSelectedIndex(Integer.parseInt(usahaUtama)-1);
//    
//
////                String selectedItem = (String) provinsiComboBox.getSelectedItem();
////                String provinsi = selectedItem.substring(0, 2);
////                selectedItem = (String) kabKotComboBox.getSelectedItem();
////                String kabKot = selectedItem.substring(0, 4);
////                selectedItem = (String) kecamatanComboBox.getSelectedItem();
////                String kecamatan = selectedItem.substring(0, 7);
////
////                // Memisahkan string perkebunan menjadi array
//                String[] perkebunanArray = perkebunan.split(",");
//
//                // Memeriksa setiap item pada JComboBox
//                for (String item : perkebunanArray) {
//                    // Mengambil karakter setelah angka 3
//                    char checkboxChar = item.charAt(1);
//
//                    // Mengubah karakter menjadi indeks untuk checkboxes
//                    int checkboxIndex = checkboxChar - 'a';
//
//                    // Memeriksa checkbox yang sesuai
//                    if (checkboxIndex >= 0 && checkboxIndex < checkboxes.length) {
//                        checkboxes[checkboxIndex].setSelected(true);
//                    }
//                }
//}
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdate().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JLabel BentukBadanHukumLabel;
    private javax.swing.JPanel DPPPanel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel HortikulturaLabel;
    private javax.swing.JLabel KIPJudulLabel;
    private javax.swing.JPanel KIPJudulPanel;
    private javax.swing.JPanel KIPPanel;
    private javax.swing.JLabel KabKotaLabel;
    private javax.swing.JLabel KecamatanLabel;
    private javax.swing.JLabel KehutananLabel;
    private javax.swing.JLabel KodeKJULabel;
    private javax.swing.JLabel NamaPerusahaanLabel;
    private javax.swing.JLabel NoFaxLabel;
    private javax.swing.JLabel NoTelepoLabel;
    private javax.swing.JLabel NoUrutLabel;
    private javax.swing.JLabel PerikananLabel;
    private javax.swing.JLabel PerkebunanLabel;
    private javax.swing.JLabel PeternakanLabel;
    private javax.swing.JLabel ProvinsiLabel;
    private javax.swing.JLabel StatusKunjunganLabel;
    private javax.swing.JLabel StatusPerusahaanLabel;
    private javax.swing.JLabel SubsektorLabel;
    private javax.swing.JLabel TahunLabel;
    private javax.swing.JLabel TanamanPanganLabel;
    private javax.swing.JLabel UsahaUtamaLabel;
    private javax.swing.JCheckBox aCheckBox;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JCheckBox bCheckBox;
    private javax.swing.JComboBox<String> bentukBadanHukumComboBox;
    private javax.swing.JCheckBox cCheckBox;
    private javax.swing.JCheckBox dCheckBox;
    private javax.swing.JCheckBox eCheckBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorAlamat;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFax;
    private javax.swing.JLabel errorKJU;
    private javax.swing.JLabel errorNoKabKot;
    private javax.swing.JLabel errorPerusahaan;
    private javax.swing.JLabel errorTahun;
    private javax.swing.JLabel errorTelepon;
    private javax.swing.JCheckBox fCheckBox;
    private javax.swing.JCheckBox gCheckBox;
    private javax.swing.JCheckBox hCheckBox;
    private javax.swing.JButton hapusButton;
    private javax.swing.JComboBox<String> hortikulturaComboBox;
    private javax.swing.JCheckBox iCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox kCheckBox;
    private javax.swing.JComboBox<String> kabKotComboBox;
    private javax.swing.JComboBox<String> kecamatanComboBox;
    private javax.swing.JComboBox<String> kehutananComboBox;
    private javax.swing.JTextField kodeKJUTextField;
    private javax.swing.JTextField namaPerusahaanTextField;
    private javax.swing.JTextField noFaxTextField;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JTextField noUrutTextField;
    private javax.swing.JComboBox<String> perikananComboBox;
    private javax.swing.JComboBox<String> peternakanComboBox;
    private javax.swing.JComboBox<String> provinsiComboBox;
    private javax.swing.JLabel space;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space4;
    private javax.swing.JLabel space5;
    private javax.swing.JComboBox<String> statusKunjunganComboBox;
    private javax.swing.JComboBox<String> statusPerusahaanComboBox;
    private javax.swing.JTextField tahunTextField;
    private javax.swing.JComboBox<String> tanamanPanganComboBox;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> usahaUtamaComboBox;
    // End of variables declaration//GEN-END:variables
}
